// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fsfihpdsggnkeuhgbevm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZzZmlocGRzZ2dua2V1aGdiZXZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxMDkyNTgsImV4cCI6MjA2MTY4NTI1OH0.erA3kFDQgeA8--qz4DwPfoJTfULF22aslSGcZN7BJY4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);